
package arthive;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JFrame;


public class AboutUs extends javax.swing.JFrame {

    /**
     * Creates new form AboutUs
     */
    public AboutUs() {
        initComponents();
        pnlArtTypeMenu.setVisible(false);
        lblUser.setText(ArtHive.staticUserName); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHome = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        lblArtType = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        pnlArtTypeMenu = new javax.swing.JPanel();
        lblVisualArt = new javax.swing.JLabel();
        lblSculpture = new javax.swing.JLabel();
        lblContemporaryArt = new javax.swing.JLabel();
        lblEvent = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblHome.setText("HOME");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHomeMousePressed(evt);
            }
        });
        getContentPane().add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        lblAbout.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblAbout.setForeground(new java.awt.Color(255, 59, 159));
        lblAbout.setText("ABOUT");
        getContentPane().add(lblAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        lblArtType.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblArtType.setText("ART TYPE ");
        lblArtType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblArtTypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblArtTypeMouseExited(evt);
            }
        });
        getContentPane().add(lblArtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, -1));

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("User");
        getContentPane().add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        pnlArtTypeMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlArtTypeMenu.setLayout(null);

        lblVisualArt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblVisualArt.setText("Visual Art");
        lblVisualArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVisualArtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVisualArtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVisualArtMousePressed(evt);
            }
        });
        pnlArtTypeMenu.add(lblVisualArt);
        lblVisualArt.setBounds(10, 10, 100, 23);

        lblSculpture.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSculpture.setText("Sculpture");
        lblSculpture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSculptureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSculptureMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSculptureMousePressed(evt);
            }
        });
        pnlArtTypeMenu.add(lblSculpture);
        lblSculpture.setBounds(10, 40, 90, 20);

        lblContemporaryArt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblContemporaryArt.setText("Contemporary Art");
        lblContemporaryArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblContemporaryArtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblContemporaryArtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblContemporaryArtMousePressed(evt);
            }
        });
        pnlArtTypeMenu.add(lblContemporaryArt);
        lblContemporaryArt.setBounds(10, 70, 140, 16);

        getContentPane().add(pnlArtTypeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 170, 100));

        lblEvent.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblEvent.setText("EVENT");
        lblEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEventMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEventMousePressed(evt);
            }
        });
        getContentPane().add(lblEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, -1));

        btnLogOut.setBackground(new java.awt.Color(242, 242, 242));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.setAlignmentX(0.1F);
        btnLogOut.setAlignmentY(0.1F);
        btnLogOut.setMaximumSize(new java.awt.Dimension(85, 28));
        btnLogOut.setMinimumSize(new java.awt.Dimension(85, 28));
        btnLogOut.setPreferredSize(new java.awt.Dimension(85, 28));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 85, 28));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Art Gallery about us.png"))); // NOI18N
        lblBackGround.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackGroundMouseClicked(evt);
            }
        });
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblArtTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtTypeMouseEntered
        
        lblArtType.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblArtType.setForeground(new Color(255, 59, 159));
        pnlArtTypeMenu.setVisible(true);
    }//GEN-LAST:event_lblArtTypeMouseEntered

    private void lblArtTypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtTypeMouseExited
        
        lblArtType.setForeground(new Color(51, 51, 51));

    }//GEN-LAST:event_lblArtTypeMouseExited

    private void lblBackGroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackGroundMouseClicked
        
        pnlArtTypeMenu.setVisible(false);
    }//GEN-LAST:event_lblBackGroundMouseClicked

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        
        lblHome.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblHome.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        
        lblHome.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMousePressed
        
        UserDashboard UserDashboardFrame = new UserDashboard();
        UserDashboardFrame.setUserValues(ArtHive.staticUserName);
        UserDashboardFrame.setVisible(true);
        
        UserDashboardFrame.pack();
        UserDashboardFrame.setExtendedState(UserDashboardFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        UserDashboardFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblHomeMousePressed

    private void lblVisualArtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualArtMouseEntered
        
        lblVisualArt.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblVisualArt.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblVisualArtMouseEntered

    private void lblVisualArtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualArtMouseExited
        
        lblVisualArt.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblVisualArtMouseExited

    private void lblVisualArtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualArtMousePressed
        
        VisualArt VisualsArtsFrame = new VisualArt();
        
        VisualsArtsFrame.setVisible(true);
        VisualsArtsFrame.pack();
        VisualsArtsFrame.setExtendedState(VisualsArtsFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        VisualsArtsFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblVisualArtMousePressed

    private void lblSculptureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSculptureMouseEntered
        
        lblSculpture.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblSculpture.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblSculptureMouseEntered

    private void lblSculptureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSculptureMouseExited
        
        lblSculpture.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblSculptureMouseExited

    private void lblSculptureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSculptureMousePressed
        
        Sculpture SculptureFrame = new Sculpture();
        SculptureFrame.setVisible(true);
        SculptureFrame.pack();
        SculptureFrame.setExtendedState(SculptureFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        SculptureFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblSculptureMousePressed

    private void lblContemporaryArtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContemporaryArtMouseEntered
        
        lblContemporaryArt.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblContemporaryArt.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblContemporaryArtMouseEntered

    private void lblContemporaryArtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContemporaryArtMouseExited
        
        lblContemporaryArt.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblContemporaryArtMouseExited

    private void lblContemporaryArtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContemporaryArtMousePressed
        
        ContemporaryArt ContemporaryArtFrame = new ContemporaryArt();
        ContemporaryArtFrame.setVisible(true);
        ContemporaryArtFrame.pack();
        ContemporaryArtFrame.setExtendedState(ContemporaryArtFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        ContemporaryArtFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblContemporaryArtMousePressed

    private void lblEventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEventMouseEntered
        
        lblEvent.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblEvent.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblEventMouseEntered

    private void lblEventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEventMouseExited
        
        lblEvent.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblEventMouseExited

    private void lblEventMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEventMousePressed
        
        Event EventFrame = new Event();
        EventFrame.setVisible(true);
        EventFrame.pack();
        EventFrame.setExtendedState(EventFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        EventFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblEventMousePressed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setExtendedState(LoginFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblArtType;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblContemporaryArt;
    private javax.swing.JLabel lblEvent;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblSculpture;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblVisualArt;
    private javax.swing.JPanel pnlArtTypeMenu;
    // End of variables declaration//GEN-END:variables
}
