
package arthive;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



public class AddEvent extends javax.swing.JFrame {

    /**
     * Creates new form AddEvent
     */
    public AddEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtExhibitionType = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtArtImage = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cmbArtist = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbArtType = new javax.swing.JComboBox<>();
        btnFile = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jdateFromDate = new com.toedter.calendar.JDateChooser();
        jdateToDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtEventPrice = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblArtPreview = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblEnquiry = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        lblArtProducts = new javax.swing.JLabel();
        lblAddEvent = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1280, 780));
        setMinimumSize(new java.awt.Dimension(1280, 780));
        setPreferredSize(new java.awt.Dimension(1280, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel1.setText("Add Event");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1280, 320));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1280, 320));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1280, 320));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Exhibition Type");

        txtExhibitionType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtExhibitionType.setForeground(new java.awt.Color(102, 102, 102));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Art Image");

        txtArtImage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtArtImage.setForeground(new java.awt.Color(102, 102, 102));

        btnSubmit.setBackground(new java.awt.Color(204, 153, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Artist");

        cmbArtist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Artist", "Salman Toor", "Paresh Maity", "Prabal Mallick", "Chandranath Das", "Ankon Mitra", "Shankho Chaudhari", "Bharati Kher", "Meera Mukherjee", "John McAllister", "Camilla Engström", "Anat Ebgi", "Amanda Baldwin" }));

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Art Type");

        cmbArtType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Art Type", "Visuals Arts", "Sculptures", "Contemporary Art" }));

        btnFile.setBackground(new java.awt.Color(204, 153, 0));
        btnFile.setForeground(new java.awt.Color(255, 255, 255));
        btnFile.setText("File");
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("From Date");

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("To Date");

        jdateFromDate.setBackground(new java.awt.Color(255, 255, 255));
        jdateFromDate.setDateFormatString("MMMM dd, yyyy");

        jdateToDate.setDateFormatString("MMMM dd, yyyy");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Event Price");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel2.setVerifyInputWhenFocusTarget(false);

        lblArtPreview.setMaximumSize(new java.awt.Dimension(300, 300));
        lblArtPreview.setMinimumSize(new java.awt.Dimension(300, 300));
        lblArtPreview.setPreferredSize(new java.awt.Dimension(20, 20));
        lblArtPreview.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblArtPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblArtPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jdateFromDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdateToDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel14)
                                .addComponent(cmbArtType, 0, 425, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addComponent(cmbArtist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(txtEventPrice))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtArtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnFile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtExhibitionType, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(602, 602, 602)
                        .addComponent(btnSubmit)))
                .addContainerGap(514, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExhibitionType, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdateFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdateToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbArtType, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEventPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1280, 410));

        lblHome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblHome.setText("HOME");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });
        getContentPane().add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 20));

        lblEnquiry.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblEnquiry.setText("VIEW ENQUIRY");
        lblEnquiry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEnquiryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEnquiryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEnquiryMousePressed(evt);
            }
        });
        getContentPane().add(lblEnquiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, -1, 20));

        btnLogOut.setBackground(new java.awt.Color(242, 242, 242));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.setAlignmentX(0.1F);
        btnLogOut.setAlignmentY(0.1F);
        btnLogOut.setMaximumSize(new java.awt.Dimension(85, 28));
        btnLogOut.setMinimumSize(new java.awt.Dimension(85, 28));
        btnLogOut.setPreferredSize(new java.awt.Dimension(85, 28));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 2, 85, 28));

        lblArtProducts.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblArtProducts.setText("ADD PRODUCTS");
        lblArtProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblArtProductsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblArtProductsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblArtProductsMousePressed(evt);
            }
        });
        getContentPane().add(lblArtProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        lblAddEvent.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblAddEvent.setForeground(new java.awt.Color(255, 59, 159));
        lblAddEvent.setText("ADD EVENT");
        getContentPane().add(lblAddEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 100, 100, -1));

        lblAdminName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAdminName.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminName.setText("Admin");
        getContentPane().add(lblAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, -1, -1));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Art Gallery Background new.png"))); // NOI18N
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("C:\\Projects\\Java\\ArtHive\\src\\artimages"));
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        lblArtPreview.setIcon(new ImageIcon(f.toString()));
        String filename = f.getAbsolutePath();
        txtArtImage.setText(filename);
        
    }//GEN-LAST:event_btnFileActionPerformed

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked

        AdminDashboard AdminDashboardFrame = new AdminDashboard();
        AdminDashboardFrame.setVisible(true);
        AdminDashboardFrame.pack();
        AdminDashboardFrame.setExtendedState(AdminDashboardFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        AdminDashboardFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered

        lblHome.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblHome.setForeground(new Color(255, 59, 159));

    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited

        lblHome.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblEnquiryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnquiryMouseEntered

        lblEnquiry.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblEnquiry.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblEnquiryMouseEntered

    private void lblEnquiryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnquiryMouseExited

        lblEnquiry.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblEnquiryMouseExited

    private void lblEnquiryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnquiryMousePressed

        EnquiryData EnquiryDataFrame = new EnquiryData();
        EnquiryDataFrame.setVisible(true);
        EnquiryDataFrame.pack();
        EnquiryDataFrame.setExtendedState(EnquiryDataFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        EnquiryDataFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblEnquiryMousePressed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setExtendedState(LoginFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        String strArtImage = txtArtImage.getText(); // Image path
        
        String strExhibitionType = txtExhibitionType.getText();
        
        DateFormat formatter = new SimpleDateFormat(jdateFromDate.getDateFormatString());
        String strFromDate = "";
        String strToDate = "";
        
        if (jdateFromDate.getDate() != null) {
            strFromDate = formatter.format(jdateFromDate.getDate());
        }
        if (jdateToDate.getDate() != null) {
            strToDate = formatter.format(jdateToDate.getDate());
        }
        
        String strArtType = String.valueOf(cmbArtType.getSelectedItem());
        String strArtist = String.valueOf(cmbArtist.getSelectedItem());
        
        String strEventPrice = txtEventPrice.getText();
        
        Component btnButton = null;
        
        if ("".equals(strArtImage)) {
            JOptionPane.showMessageDialog(btnButton, "Please Select Art Image");
            return;
        }
        
        else if ("".equals(strExhibitionType)) {
            JOptionPane.showMessageDialog(btnButton, "Please Enter Exhibition Type");
            txtExhibitionType.requestFocusInWindow();
            return;
        }
        else if ("".equals(strFromDate)) {
            JOptionPane.showMessageDialog(btnButton, "Please Select From Date");
            return;
        }
        else if ("".equals(strToDate)) {
            JOptionPane.showMessageDialog(btnButton, "Please Select To Date");
            return;
        }
        else if ("Choose Art Type".equals(strArtType)) {
            JOptionPane.showMessageDialog(btnButton, "Please Select Art Type");
            return;
        }
        else if ("Choose Artist".equals(strArtist)) {
            JOptionPane.showMessageDialog(btnButton, "Please Select Artist");
            return;
        }
        else if ("".equals(strEventPrice)) {
            JOptionPane.showMessageDialog(btnButton, "Please Enter Exhibition Event Price");
            txtExhibitionType.requestFocusInWindow();
            return;
        }
             
            try {
                

                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/arthive","root","");

                
                PreparedStatement pstmt = null;
                String query = "INSERT INTO `tblartevents` (`ImagePath`, `ExhibitionType`, `FromDate`, `ToDate`, `ArtType`, `Artist`, `EventPrice`)" +
                               "VALUES(?, ?, ? , ?, ?, ? , ?);";
                                
                
                pstmt = con.prepareStatement(query);
                
                pstmt.setString(1, strArtImage);
                pstmt.setString(2, strExhibitionType);
                pstmt.setString(3, strFromDate);
                pstmt.setString(4, strToDate);
                pstmt.setString(5, strArtType);
                pstmt.setString(6, strArtist);
                pstmt.setString(7, strEventPrice);
                
                int status = pstmt.executeUpdate();
                
                if (status > 0) {
                    Component btnNewButton = null;
                    
                    JOptionPane.showMessageDialog(btnNewButton, "Art Event added sucessfully in Gallery");
                    
                    AddEvent AddEventFrame = new AddEvent();
                    AddEventFrame.setVisible(true);
                    AddEventFrame.pack();
                    AddEventFrame.setExtendedState(AddEventFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
                    AddEventFrame.setLocationRelativeTo(null);
                    
                    this.dispose();
                }
                else{
                    Component btnNewButton = null;
                    JOptionPane.showMessageDialog(btnNewButton, "Error occur while adding product.");
                    
                }


            } catch (Exception e) {
                JOptionPane.showMessageDialog( null, e, "Message", JOptionPane.ERROR_MESSAGE);

            }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void lblArtProductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtProductsMouseEntered

        lblArtProducts.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblArtProducts.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblArtProductsMouseEntered

    private void lblArtProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtProductsMouseExited

        lblArtProducts.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblArtProductsMouseExited

    private void lblArtProductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtProductsMousePressed

        AddProduct AddProductFrame = new AddProduct();
        AddProductFrame.setVisible(true);
        AddProductFrame.pack();
        AddProductFrame.setExtendedState(AddProductFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        AddProductFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblArtProductsMousePressed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbArtType;
    private javax.swing.JComboBox<String> cmbArtist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdateFromDate;
    private com.toedter.calendar.JDateChooser jdateToDate;
    private javax.swing.JLabel lblAddEvent;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblArtPreview;
    private javax.swing.JLabel lblArtProducts;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblEnquiry;
    private javax.swing.JLabel lblHome;
    private javax.swing.JTextField txtArtImage;
    private javax.swing.JTextField txtEventPrice;
    private javax.swing.JTextField txtExhibitionType;
    // End of variables declaration//GEN-END:variables
}
