
package arthive;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

public class AddProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFeaturedImage = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDimension = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbOrientation = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cmbSize = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbArtist = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbArtType = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cmbArtMedium = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaArtDescription = new javax.swing.JTextArea();
        txtSellingPrice = new javax.swing.JTextField();
        btnFile = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblArtPreview = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblArtProducts = new javax.swing.JLabel();
        lblEnquiry = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        lblAddEvent = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1280, 780));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel1.setText("Add Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1280, 320));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1280, 320));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1280, 320));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Title");

        txtTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(102, 102, 102));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Featured Image");

        txtFeaturedImage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFeaturedImage.setForeground(new java.awt.Color(102, 102, 102));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Dimension");

        txtDimension.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDimension.setForeground(new java.awt.Color(102, 102, 102));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Orientation");

        cmbOrientation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose orientation", "Potrait", "Landscape" }));

        btnSubmit.setBackground(new java.awt.Color(204, 153, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Size");

        cmbSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Size", "Small", "Medium", "Large" }));

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Artist");

        cmbArtist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Artist", "Salman Toor", "Paresh Maity", "Prabal Mallick", "Chandranath Das", "Ankon Mitra", "Shankho Chaudhari", "Bharati Kher", "Meera Mukherjee", "John McAllister", "Camilla Engström", "Anat Ebgi", "Amanda Baldwin" }));

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Art Type");

        cmbArtType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Art Type", "Visuals Arts", "Sculptures", "Contemporary Art" }));

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Art Medium");

        cmbArtMedium.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Art Medium", "Wood and Bronze", "Acrylic on canvas", "Resin", "Mixed Media", "Bronze", "Fibre", "Steel", "Metal", "Oil on Canvas", "Oil on Linen", "Acrylics on paper", "Hand-painted on particle wood/MDF" }));
        cmbArtMedium.setToolTipText("");

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Selling Price");

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Art Product Description");

        txtAreaArtDescription.setColumns(20);
        txtAreaArtDescription.setLineWrap(true);
        txtAreaArtDescription.setRows(5);
        txtAreaArtDescription.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtAreaArtDescription);

        btnFile.setBackground(new java.awt.Color(204, 153, 0));
        btnFile.setForeground(new java.awt.Color(255, 255, 255));
        btnFile.setText("File");
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel2.setVerifyInputWhenFocusTarget(false);

        lblArtPreview.setMaximumSize(new java.awt.Dimension(300, 300));
        lblArtPreview.setMinimumSize(new java.awt.Dimension(300, 300));
        lblArtPreview.setPreferredSize(new java.awt.Dimension(300, 300));
        lblArtPreview.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblArtPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblArtPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbOrientation, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDimension, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSize, javax.swing.GroupLayout.Alignment.LEADING, 0, 425, Short.MAX_VALUE)
                    .addComponent(cmbArtist, javax.swing.GroupLayout.Alignment.LEADING, 0, 425, Short.MAX_VALUE)
                    .addComponent(cmbArtType, javax.swing.GroupLayout.Alignment.LEADING, 0, 425, Short.MAX_VALUE)
                    .addComponent(cmbArtMedium, javax.swing.GroupLayout.Alignment.LEADING, 0, 425, Short.MAX_VALUE)
                    .addComponent(txtSellingPrice, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFeaturedImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(470, 470, 470))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(631, 631, 631))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFeaturedImage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDimension, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbOrientation, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbArtType, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbArtMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1280, 410));

        lblHome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblHome.setText("HOME");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });
        getContentPane().add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 20));

        lblArtProducts.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblArtProducts.setForeground(new java.awt.Color(255, 59, 159));
        lblArtProducts.setText("ADD PRODUCTS");
        getContentPane().add(lblArtProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, 20));

        lblEnquiry.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblEnquiry.setText("VIEW ENQUIRY");
        lblEnquiry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEnquiryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEnquiryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEnquiryMousePressed(evt);
            }
        });
        getContentPane().add(lblEnquiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, -1, 20));

        btnLogOut.setBackground(new java.awt.Color(242, 242, 242));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.setAlignmentX(0.1F);
        btnLogOut.setAlignmentY(0.1F);
        btnLogOut.setMaximumSize(new java.awt.Dimension(85, 28));
        btnLogOut.setMinimumSize(new java.awt.Dimension(85, 28));
        btnLogOut.setPreferredSize(new java.awt.Dimension(85, 28));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 2, 85, 28));

        lblAddEvent.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblAddEvent.setText("ADD EVENT");
        lblAddEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddEventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddEventMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAddEventMousePressed(evt);
            }
        });
        getContentPane().add(lblAddEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 100, 100, -1));

        lblAdminName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAdminName.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminName.setText("Admin");
        getContentPane().add(lblAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, -1, -1));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Art Gallery Background new.png"))); // NOI18N
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        

        String strTitle = txtTitle.getText();
        String strFeaturedImage = txtFeaturedImage.getText(); // Image path
        String strDimension = txtDimension.getText();
        String strOrientation = String.valueOf(cmbOrientation.getSelectedItem());
        String strSize = String.valueOf(cmbSize.getSelectedItem());
        String strArtist = String.valueOf(cmbArtist.getSelectedItem());
        String strArtType = String.valueOf(cmbArtType.getSelectedItem());
        String strArtMedium = String.valueOf(cmbArtMedium.getSelectedItem());
        String strSellingPrice = txtSellingPrice.getText();
        String strArtDescription = txtAreaArtDescription.getText();
        String strReferenceNumber = new SimpleDateFormat("yyyyMMddHHmmss").format(new java.util.Date());


        Component btnButton = null;
        
        if ("".equals(strTitle)) {
            JOptionPane.showMessageDialog(btnButton, "Please Enter Title");
            txtTitle.requestFocusInWindow();
            return;
        }
        else if ("".equals(strFeaturedImage)) {
            JOptionPane.showMessageDialog(btnButton, "Please Select Featured Image");
            return;
        }
        else if ("".equals(strDimension)) {
            JOptionPane.showMessageDialog(btnButton, "Please Enter Dimension");
            return;
        }
        else if ("Choose orientation".equals(strOrientation)) {
            JOptionPane.showMessageDialog(btnButton, "Please Select Orientation");
            return;
        }
        
        if ("Choose Size".equals(strSize)) {
            JOptionPane.showMessageDialog(btnButton, "Please Select Size");
            return;
        }
        else if ("Choose Artist".equals(strArtist)) {
            JOptionPane.showMessageDialog(btnButton, "Please Select Artist");
            return;
        }
        else if ("Choose Art Type".equals(strArtType)) {
            JOptionPane.showMessageDialog(btnButton, "Please Select Art Type");
            return;
        }
        else if ("Choose Art Medium".equals(strArtMedium)) {
            JOptionPane.showMessageDialog(btnButton, "Please Select Art Medium");
            return;
        }
        else if ("".equals(strSellingPrice)) {
            JOptionPane.showMessageDialog(btnButton, "Please Enter Selling Price");
            return;
        }
        else if ("".equals(strArtDescription)) {
            JOptionPane.showMessageDialog(btnButton, "Please Enter Art Description");
            return;
        }
        

             
            try {
                

                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/arthive","root","");

                
                PreparedStatement pstmt = null;
                String query = "INSERT INTO `tblartproducts` (`Title`, `ImagePath`, `Dimension`, `Orientation`, `ImageSize`, `Artist`, `ArtType`, `ArtMedium`, `SellingPrice`, `ProductDescription`, `ReferenceNumber`)" +
                               "VALUES(?, ?, ? , ?, ?, ? , ?, ?, ? , ?, ?);";
                                
                
                pstmt = con.prepareStatement(query);
                
                pstmt.setString(1, strTitle);
                pstmt.setString(2, strFeaturedImage);
                pstmt.setString(3, strDimension);
                pstmt.setString(4, strOrientation);
                pstmt.setString(5, strSize);
                pstmt.setString(6, strArtist);
                pstmt.setString(7, strArtType);
                pstmt.setString(8, strArtMedium);
                pstmt.setString(9, strSellingPrice);
                pstmt.setString(10, strArtDescription);
                pstmt.setString(11, strReferenceNumber);
                
                int status = pstmt.executeUpdate();
                
                
                if (status > 0) {
                    Component btnNewButton = null;
                    
                    JOptionPane.showMessageDialog(btnNewButton, "Art Product added sucessfully in Gallery");
                    
                    AddProduct AddProductFrame = new AddProduct();
                    
                    AddProductFrame.setVisible(true);
                    AddProductFrame.pack();
                    AddProductFrame.setExtendedState(AddProductFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
                    AddProductFrame.setLocationRelativeTo(null);
                    
                    this.dispose();
                }
                else{
                    Component btnNewButton = null;
                    JOptionPane.showMessageDialog(btnNewButton, "Error occur while adding product.");
                    
                }


            } catch (Exception e) {
                JOptionPane.showMessageDialog( null, e, "Message", JOptionPane.ERROR_MESSAGE);

            }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        
        AdminDashboard AdminDashboardFrame = new AdminDashboard();
        AdminDashboardFrame.setVisible(true);
        AdminDashboardFrame.pack();
        AdminDashboardFrame.setExtendedState(AdminDashboardFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        AdminDashboardFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        
        lblHome.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblHome.setForeground(new Color(255, 59, 159));
        
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        
        lblHome.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblHomeMouseExited

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("C:\\Projects\\Java\\ArtHive\\src\\artimages"));
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        lblArtPreview.setIcon(new ImageIcon(f.toString()));
        String filename = f.getAbsolutePath();
        txtFeaturedImage.setText(filename);
    }//GEN-LAST:event_btnFileActionPerformed

    private void lblEnquiryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnquiryMouseEntered
        
        lblEnquiry.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblEnquiry.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblEnquiryMouseEntered

    private void lblEnquiryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnquiryMouseExited
        
        lblEnquiry.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblEnquiryMouseExited

    private void lblEnquiryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnquiryMousePressed
        
        EnquiryData EnquiryDataFrame = new EnquiryData();
        EnquiryDataFrame.setVisible(true);
        EnquiryDataFrame.pack();
        EnquiryDataFrame.setExtendedState(EnquiryDataFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        EnquiryDataFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblEnquiryMousePressed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setExtendedState(LoginFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void lblAddEventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddEventMouseEntered
        // TODO add your handling code here:
        lblAddEvent.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblAddEvent.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblAddEventMouseEntered

    private void lblAddEventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddEventMouseExited
        // TODO add your handling code here:
        lblEnquiry.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblAddEventMouseExited

    private void lblAddEventMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddEventMousePressed
        // TODO add your handling code here:
        AddEvent AddEventFrame = new AddEvent();
        AddEventFrame.setVisible(true);
        AddEventFrame.pack();
        AddEventFrame.setExtendedState(AddEventFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        AddEventFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblAddEventMousePressed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbArtMedium;
    private javax.swing.JComboBox<String> cmbArtType;
    private javax.swing.JComboBox<String> cmbArtist;
    private javax.swing.JComboBox<String> cmbOrientation;
    private javax.swing.JComboBox<String> cmbSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddEvent;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblArtPreview;
    private javax.swing.JLabel lblArtProducts;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblEnquiry;
    private javax.swing.JLabel lblHome;
    private javax.swing.JTextArea txtAreaArtDescription;
    private javax.swing.JTextField txtDimension;
    private javax.swing.JTextField txtFeaturedImage;
    private javax.swing.JTextField txtSellingPrice;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
