
package arthive;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JFrame;


public class AdminDashboard extends javax.swing.JFrame {


    public void setAdminValues(String adminName) {
        
        lblAdminName.setText(adminName);
    }
    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminName = new javax.swing.JLabel();
        lblArtProducts = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblEnquiry = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        lblAddEvent = new javax.swing.JLabel();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdminName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAdminName.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminName.setText("Admin");
        getContentPane().add(lblAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        lblArtProducts.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblArtProducts.setText("ADD PRODUCTS");
        lblArtProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblArtProductsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblArtProductsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblArtProductsMousePressed(evt);
            }
        });
        getContentPane().add(lblArtProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        lblHome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 59, 159));
        lblHome.setText("HOME");
        getContentPane().add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        lblEnquiry.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblEnquiry.setText("VIEW ENQUIRY");
        lblEnquiry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEnquiryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEnquiryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEnquiryMousePressed(evt);
            }
        });
        getContentPane().add(lblEnquiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, -1, -1));

        btnLogOut.setBackground(new java.awt.Color(242, 242, 242));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.setAlignmentX(0.1F);
        btnLogOut.setAlignmentY(0.1F);
        btnLogOut.setMaximumSize(new java.awt.Dimension(79, 28));
        btnLogOut.setMinimumSize(new java.awt.Dimension(79, 28));
        btnLogOut.setPreferredSize(new java.awt.Dimension(79, 28));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 85, 28));

        lblAddEvent.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblAddEvent.setText("ADD EVENT");
        lblAddEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddEventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddEventMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAddEventMousePressed(evt);
            }
        });
        getContentPane().add(lblAddEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 120, 100, -1));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Art Gallery.png"))); // NOI18N
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblArtProductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtProductsMouseEntered
        
        lblArtProducts.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblArtProducts.setForeground(new Color(255, 59, 159));
        
    }//GEN-LAST:event_lblArtProductsMouseEntered

    private void lblArtProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtProductsMouseExited
        
        lblArtProducts.setForeground(new Color(51, 51, 51));

    }//GEN-LAST:event_lblArtProductsMouseExited

    private void lblEnquiryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnquiryMouseEntered
        
        lblEnquiry.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblEnquiry.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblEnquiryMouseEntered

    private void lblEnquiryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnquiryMouseExited
        
        lblEnquiry.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblEnquiryMouseExited

    private void lblEnquiryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnquiryMousePressed
        
        EnquiryData EnquiryDataFrame = new EnquiryData();
        EnquiryDataFrame.setVisible(true);
        EnquiryDataFrame.pack();
        EnquiryDataFrame.setExtendedState(EnquiryDataFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        EnquiryDataFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblEnquiryMousePressed

    private void lblArtProductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtProductsMousePressed
        
        AddProduct AddProductFrame = new AddProduct();
        AddProductFrame.setVisible(true);
        AddProductFrame.pack();
        AddProductFrame.setExtendedState(AddProductFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        AddProductFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblArtProductsMousePressed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setExtendedState(LoginFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void lblAddEventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddEventMouseEntered
        // TODO add your handling code here:
        lblAddEvent.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblAddEvent.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblAddEventMouseEntered

    private void lblAddEventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddEventMouseExited
        // TODO add your handling code here:
        lblEnquiry.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblAddEventMouseExited

    private void lblAddEventMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddEventMousePressed
        // TODO add your handling code here:
        AddEvent AddEventFrame = new AddEvent();
        AddEventFrame.setVisible(true);
        AddEventFrame.pack();
        AddEventFrame.setExtendedState(AddEventFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        AddEventFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblAddEventMousePressed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel lblAddEvent;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblArtProducts;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblEnquiry;
    private javax.swing.JLabel lblHome;
    // End of variables declaration//GEN-END:variables
}
