
package arthive;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class ArtDetails extends javax.swing.JFrame {
    
    public void getArtproductIdData(String artproductId) {
        
        lblArtproductId.setVisible(false);
        lblArtproductId.setText(artproductId);
        
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/arthive","root","");
            
            Statement st = con.createStatement();
            
            
                ResultSet rs = st.executeQuery("select * from tblartproducts where ID='" + artproductId + "'");
                
                int recordCount = 0;
                while(rs.next()){
                    recordCount++;

                    lblTitleArtist.setText(rs.getString("Title") + "(" + rs.getString("Artist") + ")");
                    lblSize.setText(rs.getString("ImageSize"));
                    lblDimension.setText(rs.getString("Dimension"));
                    lblOrientation.setText(rs.getString("Orientation"));
                    lblArtTypes.setText(rs.getString("ArtType"));
                    lblArtMedium.setText(rs.getString("ArtMedium"));

                    lblDescTitle.setText(rs.getString("Title"));
                    txtAreaProductDescription.setText(rs.getString("ProductDescription"));

                    lblImage.setIcon(new ImageIcon(rs.getString("ImagePath")));

                    lblReferenceNumber.setText(rs.getString("ReferenceNumber"));
                      
                }
                if(recordCount == 0){
                    JOptionPane.showMessageDialog( null, "Record Not Found.", "Message", JOptionPane.ERROR_MESSAGE);
                }

            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog( null, e, "Message", JOptionPane.ERROR_MESSAGE);
            
        }
    }
    /**
     * Creates new form ArtDetails
     */
    public ArtDetails() {
        initComponents();
        pnlArtTypeMenu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblTitleArtist = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnEnquiry = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblDescTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaProductDescription = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        lblReferenceNumber = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblDimension = new javax.swing.JLabel();
        lblOrientation = new javax.swing.JLabel();
        lblArtTypes = new javax.swing.JLabel();
        lblArtMedium = new javax.swing.JLabel();
        lblArtproductId = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblArtType = new javax.swing.JLabel();
        pnlArtTypeMenu = new javax.swing.JPanel();
        lblVisualArt = new javax.swing.JLabel();
        lblSculpture = new javax.swing.JLabel();
        lblContemporaryArt = new javax.swing.JLabel();
        lblEvent = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel1.setText("Visual Art");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1280, 320));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1280, 320));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1280, 320));
        jScrollPane1.setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 900));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentX(0.2F);
        jPanel2.setAlignmentY(0.2F);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artimages/1.RECIPE (Visual Arts) new.png"))); // NOI18N
        lblImage.setAlignmentX(0.2F);
        lblImage.setAlignmentY(0.2F);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        lblTitleArtist.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitleArtist.setForeground(new java.awt.Color(204, 153, 0));
        lblTitleArtist.setText("Title(Artist)");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Size : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Dimension : ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Orientation : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Art Types : ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Art Medium : ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Art Reference Number : ");

        btnEnquiry.setBackground(new java.awt.Color(204, 153, 0));
        btnEnquiry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEnquiry.setForeground(new java.awt.Color(255, 255, 255));
        btnEnquiry.setText("Enquiry");
        btnEnquiry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnquiry.setMaximumSize(new java.awt.Dimension(80, 30));
        btnEnquiry.setMinimumSize(new java.awt.Dimension(80, 30));
        btnEnquiry.setPreferredSize(new java.awt.Dimension(80, 30));
        btnEnquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnquiryActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDescTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescTitle.setText("lblDescTitle");

        jScrollPane3.setBorder(null);

        txtAreaProductDescription.setColumns(20);
        txtAreaProductDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAreaProductDescription.setLineWrap(true);
        txtAreaProductDescription.setRows(5);
        txtAreaProductDescription.setText("txtAreaProductDescription");
        txtAreaProductDescription.setWrapStyleWord(true);
        txtAreaProductDescription.setBorder(null);
        jScrollPane3.setViewportView(txtAreaProductDescription);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDescTitle))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblDescTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 153, 0));
        jLabel12.setText("DESCRIPTION");

        lblReferenceNumber.setText("lblReferenceNumber");

        lblSize.setText("lblText");

        lblDimension.setText("lblDimension");

        lblOrientation.setText("lblOrientation");

        lblArtTypes.setText("lblArtTypes");

        lblArtMedium.setText("lblArtMedium");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDimension))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSize))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblOrientation))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblArtTypes))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblArtMedium))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblReferenceNumber))
                                    .addComponent(btnEnquiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(lblTitleArtist)
                                .addGap(63, 63, 63)
                                .addComponent(lblArtproductId))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitleArtist)
                            .addComponent(lblArtproductId))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblSize))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblDimension))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblOrientation))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblArtTypes))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblArtMedium))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblReferenceNumber))
                        .addGap(40, 40, 40)
                        .addComponent(btnEnquiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1280, 390));

        lblAbout.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblAbout.setText("ABOUT");
        lblAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAboutMousePressed(evt);
            }
        });
        getContentPane().add(lblAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        lblHome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblHome.setText("HOME");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHomeMousePressed(evt);
            }
        });
        getContentPane().add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        lblArtType.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblArtType.setForeground(new java.awt.Color(255, 59, 159));
        lblArtType.setText("ART TYPE ");
        lblArtType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblArtTypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblArtTypeMouseExited(evt);
            }
        });
        getContentPane().add(lblArtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        pnlArtTypeMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlArtTypeMenu.setLayout(null);

        lblVisualArt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblVisualArt.setText("Visual Art");
        lblVisualArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVisualArtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVisualArtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVisualArtMousePressed(evt);
            }
        });
        pnlArtTypeMenu.add(lblVisualArt);
        lblVisualArt.setBounds(10, 10, 100, 23);

        lblSculpture.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSculpture.setText("Sculpture");
        lblSculpture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSculptureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSculptureMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSculptureMousePressed(evt);
            }
        });
        pnlArtTypeMenu.add(lblSculpture);
        lblSculpture.setBounds(10, 40, 90, 20);

        lblContemporaryArt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblContemporaryArt.setText("Contemporary Art");
        lblContemporaryArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblContemporaryArtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblContemporaryArtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblContemporaryArtMousePressed(evt);
            }
        });
        pnlArtTypeMenu.add(lblContemporaryArt);
        lblContemporaryArt.setBounds(10, 70, 140, 16);

        getContentPane().add(pnlArtTypeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 170, 100));

        lblEvent.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblEvent.setText("EVENT");
        lblEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEventMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEventMousePressed(evt);
            }
        });
        getContentPane().add(lblEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, -1, -1));

        btnLogOut.setBackground(new java.awt.Color(242, 242, 242));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.setAlignmentX(0.1F);
        btnLogOut.setAlignmentY(0.1F);
        btnLogOut.setMaximumSize(new java.awt.Dimension(79, 28));
        btnLogOut.setMinimumSize(new java.awt.Dimension(79, 28));
        btnLogOut.setPreferredSize(new java.awt.Dimension(79, 28));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 2, 85, 28));

        lblBackGround.setBackground(new java.awt.Color(255, 255, 255));
        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Art Gallery Background new.png"))); // NOI18N
        lblBackGround.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackGroundMouseClicked(evt);
            }
        });
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseEntered
        
        lblAbout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblAbout.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblAboutMouseEntered

    private void lblAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseExited
        
        lblAbout.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblAboutMouseExited

    private void lblAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMousePressed
        
        AboutUs AboutUsFrame = new AboutUs();
        AboutUsFrame.setVisible(true);
        AboutUsFrame.pack();
        AboutUsFrame.setExtendedState(AboutUsFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        AboutUsFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblAboutMousePressed

    private void btnEnquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnquiryActionPerformed
        
        Enquiry EnquiryFrame = new Enquiry();
        EnquiryFrame.submitEnquirydData(lblArtproductId.getText());
        EnquiryFrame.setVisible(true);
        EnquiryFrame.pack();
        EnquiryFrame.setExtendedState(EnquiryFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        EnquiryFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnEnquiryActionPerformed

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        
        lblHome.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblHome.setForeground(new Color(255, 59, 159));

    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        
        lblHome.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMousePressed
        
        UserDashboard UserDashboardFrame = new UserDashboard();
        UserDashboardFrame.setUserValues(ArtHive.staticUserName);
        UserDashboardFrame.setVisible(true);
        
        UserDashboardFrame.pack();
        UserDashboardFrame.setExtendedState(UserDashboardFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        UserDashboardFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblHomeMousePressed

    private void lblArtTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtTypeMouseEntered
        
        lblArtType.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblArtType.setForeground(new Color(255, 59, 159));
        pnlArtTypeMenu.setVisible(true);
    }//GEN-LAST:event_lblArtTypeMouseEntered

    private void lblArtTypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtTypeMouseExited
        
        lblArtType.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblArtTypeMouseExited

    private void lblVisualArtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualArtMouseEntered
        
        lblVisualArt.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblVisualArt.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblVisualArtMouseEntered

    private void lblVisualArtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualArtMouseExited
        
        lblVisualArt.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblVisualArtMouseExited

    private void lblVisualArtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualArtMousePressed
        
        VisualArt VisualsArtsFrame = new VisualArt();
        VisualsArtsFrame.setVisible(true);
        VisualsArtsFrame.pack();
        VisualsArtsFrame.setExtendedState(VisualsArtsFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        VisualsArtsFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblVisualArtMousePressed

    private void lblSculptureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSculptureMouseEntered
        
        lblSculpture.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblSculpture.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblSculptureMouseEntered

    private void lblSculptureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSculptureMouseExited
        
        lblSculpture.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblSculptureMouseExited

    private void lblSculptureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSculptureMousePressed
        
        Sculpture SculptureFrame = new Sculpture();
        SculptureFrame.setVisible(true);
        SculptureFrame.pack();
        SculptureFrame.setExtendedState(SculptureFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        SculptureFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblSculptureMousePressed

    private void lblContemporaryArtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContemporaryArtMouseEntered
        
        lblContemporaryArt.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblContemporaryArt.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblContemporaryArtMouseEntered

    private void lblContemporaryArtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContemporaryArtMouseExited
        
        lblContemporaryArt.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblContemporaryArtMouseExited

    private void lblContemporaryArtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContemporaryArtMousePressed
        
        ContemporaryArt ContemporaryArtFrame = new ContemporaryArt();
        ContemporaryArtFrame.setVisible(true);
        ContemporaryArtFrame.pack();
        ContemporaryArtFrame.setExtendedState(ContemporaryArtFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        ContemporaryArtFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblContemporaryArtMousePressed

    private void lblBackGroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackGroundMouseClicked
        
        pnlArtTypeMenu.setVisible(false);
    }//GEN-LAST:event_lblBackGroundMouseClicked

    private void lblEventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEventMouseEntered
        
        lblEvent.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblEvent.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblEventMouseEntered

    private void lblEventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEventMouseExited
        
        lblEvent.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblEventMouseExited

    private void lblEventMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEventMousePressed
        
        Event EventFrame = new Event();
        EventFrame.setVisible(true);
        EventFrame.pack();
        EventFrame.setExtendedState(EventFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        EventFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblEventMousePressed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setExtendedState(LoginFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnquiry;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblArtMedium;
    private javax.swing.JLabel lblArtType;
    private javax.swing.JLabel lblArtTypes;
    private javax.swing.JLabel lblArtproductId;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblContemporaryArt;
    private javax.swing.JLabel lblDescTitle;
    private javax.swing.JLabel lblDimension;
    private javax.swing.JLabel lblEvent;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblOrientation;
    private javax.swing.JLabel lblReferenceNumber;
    private javax.swing.JLabel lblSculpture;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblTitleArtist;
    private javax.swing.JLabel lblVisualArt;
    private javax.swing.JPanel pnlArtTypeMenu;
    private javax.swing.JTextArea txtAreaProductDescription;
    // End of variables declaration//GEN-END:variables
}
