
package arthive;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;

public class Enquiry extends javax.swing.JFrame {
    
    public void submitEnquirydData(String artproductId) {
        
        lblArtproductId.setVisible(false);
        lblArtproductId.setText(artproductId);
        
    }

    /**
     * Creates new form Enquiry
     */
    public Enquiry() {
        initComponents();
        pnlArtTypeMenu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaMessage = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        lblArtproductId = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblArtType = new javax.swing.JLabel();
        pnlArtTypeMenu = new javax.swing.JPanel();
        lblVisualArt = new javax.swing.JLabel();
        lblSculpture = new javax.swing.JLabel();
        lblContemporaryArt = new javax.swing.JLabel();
        lblEvent = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel1.setText("Enquiry");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1280, 320));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1280, 320));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1280, 320));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Full Name");

        txtFullName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFullName.setForeground(new java.awt.Color(102, 102, 102));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Email");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(102, 102, 102));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Mobile Number");

        txtMobileNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMobileNumber.setForeground(new java.awt.Color(102, 102, 102));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Message");

        txtAreaMessage.setColumns(20);
        txtAreaMessage.setLineWrap(true);
        txtAreaMessage.setRows(5);
        txtAreaMessage.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtAreaMessage);

        btnSend.setBackground(new java.awt.Color(204, 153, 0));
        btnSend.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(454, 454, 454)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166)))
                        .addContainerGap(460, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblArtproductId)
                        .addGap(490, 490, 490))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblArtproductId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(458, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1280, 390));

        lblAbout.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblAbout.setText("ABOUT");
        lblAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAboutMousePressed(evt);
            }
        });
        getContentPane().add(lblAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        lblHome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblHome.setText("HOME");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHomeMousePressed(evt);
            }
        });
        getContentPane().add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        lblArtType.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblArtType.setForeground(new java.awt.Color(255, 59, 159));
        lblArtType.setText("ART TYPE ");
        lblArtType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblArtTypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblArtTypeMouseExited(evt);
            }
        });
        getContentPane().add(lblArtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        pnlArtTypeMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlArtTypeMenu.setLayout(null);

        lblVisualArt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblVisualArt.setText("Visual Art");
        lblVisualArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVisualArtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVisualArtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVisualArtMousePressed(evt);
            }
        });
        pnlArtTypeMenu.add(lblVisualArt);
        lblVisualArt.setBounds(10, 10, 100, 23);

        lblSculpture.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSculpture.setText("Sculpture");
        lblSculpture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSculptureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSculptureMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSculptureMousePressed(evt);
            }
        });
        pnlArtTypeMenu.add(lblSculpture);
        lblSculpture.setBounds(10, 40, 90, 20);

        lblContemporaryArt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblContemporaryArt.setText("Contemporary Art");
        lblContemporaryArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblContemporaryArtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblContemporaryArtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblContemporaryArtMousePressed(evt);
            }
        });
        pnlArtTypeMenu.add(lblContemporaryArt);
        lblContemporaryArt.setBounds(10, 70, 140, 16);

        getContentPane().add(pnlArtTypeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 170, 90));

        lblEvent.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblEvent.setText("EVENT");
        lblEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEventMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEventMousePressed(evt);
            }
        });
        getContentPane().add(lblEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, -1, -1));

        btnLogOut.setBackground(new java.awt.Color(242, 242, 242));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.setAlignmentX(0.1F);
        btnLogOut.setAlignmentY(0.1F);
        btnLogOut.setMaximumSize(new java.awt.Dimension(79, 28));
        btnLogOut.setMinimumSize(new java.awt.Dimension(79, 28));
        btnLogOut.setPreferredSize(new java.awt.Dimension(79, 28));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 2, 85, 28));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Art Gallery Background new.png"))); // NOI18N
        lblBackGround.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackGroundMouseClicked(evt);
            }
        });
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseEntered
        
        lblAbout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblAbout.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblAboutMouseEntered

    private void lblAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseExited
        
        lblAbout.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblAboutMouseExited

    private void lblAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMousePressed
        
        AboutUs AboutUsFrame = new AboutUs();
        AboutUsFrame.setVisible(true);
        AboutUsFrame.pack();
        AboutUsFrame.setExtendedState(AboutUsFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        AboutUsFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblAboutMousePressed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        
        
        String strEnquiryNumber = new SimpleDateFormat("yyMMddHHmmss").format(new java.util.Date());
        String strArtproductId = lblArtproductId.getText();
        
        String strFullName = txtFullName.getText();
        String strEmail = txtEmail.getText();
        String strMobileNumber = txtMobileNumber.getText();
        String strAreaMessage = txtAreaMessage.getText();

        


        Component btnButton = null;
        
        if ("".equals(strFullName)) {
            JOptionPane.showMessageDialog(btnButton, "Please Enter Full Name");
            txtFullName.requestFocusInWindow();
            return;
        }
        else if ("".equals(strEmail)) {
            JOptionPane.showMessageDialog(btnButton, "Please Enter Email");
            return;
        }
        
        else if (!strEmail.matches("^[A-Za-z0-9_.]+[@][A-Za-z.]+$")) {
            JOptionPane.showMessageDialog(btnButton, "Please Enter Valid Email");
            return;
        }
        else if ("".equals(strMobileNumber)) {
            JOptionPane.showMessageDialog(btnButton, "Please Enter Mobile Number");
            return;
        }
        
        else if ("".equals(strAreaMessage)) {
            JOptionPane.showMessageDialog(btnButton, "Please Enter Message");
            return;
        }
        

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/arthive","root","");

                PreparedStatement pstmt = null;
                String query = "INSERT INTO `tblenquiry` (`EnquiryNumber`, `ArtproductId`, `FullName`, `Email`, `MobileNumber`, `Message`)" +
                               "VALUES(?, ?, ? , ?, ?, ?);";
                
                pstmt = con.prepareStatement(query);
                
                pstmt.setString(1, strEnquiryNumber);
                pstmt.setString(2, strArtproductId);
                pstmt.setString(3, strFullName);
                pstmt.setString(4, strEmail);
                pstmt.setString(5, strMobileNumber);
                pstmt.setString(6, strAreaMessage);
                
                int status = pstmt.executeUpdate();
                
                if (status > 0) {
                    Component btnNewButton = null;
                    
                    JOptionPane.showMessageDialog(btnNewButton, "Your enquiry successfully send. Your Enquiry number is " + strEnquiryNumber);
                    
                    VisualArt VisualArtFrame = new VisualArt();
                    VisualArtFrame.setVisible(true);
                    VisualArtFrame.pack();
                    VisualArtFrame.setExtendedState(VisualArtFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
                    VisualArtFrame.setLocationRelativeTo(null);
                    
                    this.dispose();
                }
                else{
                    Component btnNewButton = null;
                    JOptionPane.showMessageDialog(btnNewButton, "Error occur while adding product.");
                }


            } catch (Exception e) {
                JOptionPane.showMessageDialog( null, e, "Message", JOptionPane.ERROR_MESSAGE);

            }
    }//GEN-LAST:event_btnSendActionPerformed

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        
        lblHome.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblHome.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        
        lblHome.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMousePressed
        
        UserDashboard UserDashboardFrame = new UserDashboard();
        UserDashboardFrame.setUserValues(ArtHive.staticUserName);
        UserDashboardFrame.setVisible(true);
        
        UserDashboardFrame.pack();
        UserDashboardFrame.setExtendedState(UserDashboardFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        UserDashboardFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblHomeMousePressed

    private void lblArtTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtTypeMouseEntered
        
        lblArtType.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblArtType.setForeground(new Color(255, 59, 159));
        pnlArtTypeMenu.setVisible(true);
    }//GEN-LAST:event_lblArtTypeMouseEntered

    private void lblArtTypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtTypeMouseExited
        
        lblArtType.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblArtTypeMouseExited

    private void lblVisualArtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualArtMouseEntered
        
        lblVisualArt.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblVisualArt.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblVisualArtMouseEntered

    private void lblVisualArtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualArtMouseExited
        
        lblVisualArt.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblVisualArtMouseExited

    private void lblVisualArtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualArtMousePressed
        
        VisualArt VisualsArtsFrame = new VisualArt();
        VisualsArtsFrame.setVisible(true);
        VisualsArtsFrame.pack();
        VisualsArtsFrame.setExtendedState(VisualsArtsFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        VisualsArtsFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblVisualArtMousePressed

    private void lblSculptureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSculptureMouseEntered
        
        lblSculpture.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblSculpture.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblSculptureMouseEntered

    private void lblSculptureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSculptureMouseExited
        
        lblSculpture.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblSculptureMouseExited

    private void lblSculptureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSculptureMousePressed
        
        Sculpture SculptureFrame = new Sculpture();
        SculptureFrame.setVisible(true);
        SculptureFrame.pack();
        SculptureFrame.setExtendedState(SculptureFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        SculptureFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblSculptureMousePressed

    private void lblContemporaryArtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContemporaryArtMouseEntered
        
        lblContemporaryArt.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblContemporaryArt.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblContemporaryArtMouseEntered

    private void lblContemporaryArtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContemporaryArtMouseExited
        
        lblContemporaryArt.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblContemporaryArtMouseExited

    private void lblContemporaryArtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContemporaryArtMousePressed
        
        ContemporaryArt ContemporaryArtFrame = new ContemporaryArt();
        ContemporaryArtFrame.setVisible(true);
        ContemporaryArtFrame.pack();
        ContemporaryArtFrame.setExtendedState(ContemporaryArtFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        ContemporaryArtFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblContemporaryArtMousePressed

    private void lblBackGroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackGroundMouseClicked
        
        pnlArtTypeMenu.setVisible(false);
    }//GEN-LAST:event_lblBackGroundMouseClicked

    private void lblEventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEventMouseEntered
        
        lblEvent.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblEvent.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblEventMouseEntered

    private void lblEventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEventMouseExited
        
        lblEvent.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblEventMouseExited

    private void lblEventMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEventMousePressed
        
        Event EventFrame = new Event();
        EventFrame.setVisible(true);
        EventFrame.pack();
        EventFrame.setExtendedState(EventFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        EventFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblEventMousePressed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setExtendedState(LoginFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblArtType;
    private javax.swing.JLabel lblArtproductId;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblContemporaryArt;
    private javax.swing.JLabel lblEvent;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblSculpture;
    private javax.swing.JLabel lblVisualArt;
    private javax.swing.JPanel pnlArtTypeMenu;
    private javax.swing.JTextArea txtAreaMessage;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtMobileNumber;
    // End of variables declaration//GEN-END:variables
}
