
package arthive;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class EnquiryData extends javax.swing.JFrame {

    /**
     * Creates new form EnquiryData
     */
    public EnquiryData() {
        initComponents();
        tblEnquiry.getTableHeader().setFont(new Font("Segoe UI ", Font.BOLD, 16));
        tblEnquiry.getTableHeader().setOpaque(false);
        tblEnquiry.getTableHeader().setBackground(new Color(204,153,0));
        tblEnquiry.getTableHeader().setForeground(new Color(255,255,255));
                
        try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/arthive","root","");

                PreparedStatement pstmt = null;
                pstmt = con.prepareStatement("select * from tblenquiry");

                ResultSet rs = pstmt.executeQuery();

                ResultSetMetaData rsmd = rs.getMetaData();

                int count = rsmd.getColumnCount();
                DefaultTableModel dtm = (DefaultTableModel) tblEnquiry.getModel();
                dtm.setRowCount(0);

                int recordCount = 0;
            
                while(rs.next()){

                    recordCount++;

                    Vector vctr = new Vector();

                    for (int i = 1; i <= count; i++) {
                        vctr.add(rs.getString("EnquiryNumber"));
                        vctr.add(rs.getString("FullName"));
                        vctr.add(rs.getString("Email"));
                        vctr.add(rs.getString("MobileNumber"));
                        vctr.add(rs.getString("Message"));
                        vctr.add(rs.getString("EnquiryDate"));
                    }
                    
                    dtm.addRow(vctr);

                  }
            
                if(recordCount == 0){
                    tblEnquiry.setVisible(false);
                    
                    JOptionPane.showMessageDialog( null, "No record to display.", "Message", JOptionPane.ERROR_MESSAGE);
                }

            }
            
        catch (Exception e) {
            JOptionPane.showMessageDialog( null, e, "Message", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        lblArtProducts = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEnquiry = new javax.swing.JTable();
        lblEnquiry = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        lblAddEvent = new javax.swing.JLabel();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel1.setText("Enquiry Report");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        lblAdminName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAdminName.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminName.setText("Admin");
        getContentPane().add(lblAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, -1, -1));

        lblArtProducts.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblArtProducts.setText("ADD PRODUCTS");
        lblArtProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblArtProductsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblArtProductsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblArtProductsMousePressed(evt);
            }
        });
        getContentPane().add(lblArtProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        lblHome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblHome.setText("HOME");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHomeMousePressed(evt);
            }
        });
        getContentPane().add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1280, 320));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1280, 320));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1280, 320));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblEnquiry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblEnquiry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Enquiry Number", "Full Name", "Email", "Mobile Number", "Message", "EnquiryDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEnquiry.setFocusable(false);
        tblEnquiry.setRowHeight(25);
        tblEnquiry.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblEnquiry.setSelectionForeground(new java.awt.Color(204, 153, 0));
        tblEnquiry.setShowGrid(false);
        tblEnquiry.setShowHorizontalLines(true);
        tblEnquiry.getTableHeader().setReorderingAllowed(false);
        tblEnquiry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEnquiryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEnquiry);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1280, 390));

        lblEnquiry.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblEnquiry.setForeground(new java.awt.Color(255, 59, 159));
        lblEnquiry.setText("VIEW ENQUIRY");
        getContentPane().add(lblEnquiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, -1, -1));

        btnLogOut.setBackground(new java.awt.Color(242, 242, 242));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.setAlignmentX(0.1F);
        btnLogOut.setAlignmentY(0.1F);
        btnLogOut.setMaximumSize(new java.awt.Dimension(79, 28));
        btnLogOut.setMinimumSize(new java.awt.Dimension(79, 28));
        btnLogOut.setPreferredSize(new java.awt.Dimension(79, 28));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 2, 85, 28));

        lblAddEvent.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblAddEvent.setText("ADD EVENT");
        lblAddEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddEventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddEventMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAddEventMousePressed(evt);
            }
        });
        getContentPane().add(lblAddEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 100, 100, -1));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Art Gallery Background new.png"))); // NOI18N
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblArtProductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtProductsMouseEntered
        
        lblArtProducts.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblArtProducts.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblArtProductsMouseEntered

    private void lblArtProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtProductsMouseExited
        
        lblArtProducts.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblArtProductsMouseExited

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        
        lblHome.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblHome.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        
        lblEnquiry.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMousePressed
        
        AdminDashboard AdminDashboardFrame = new AdminDashboard();
        AdminDashboardFrame.setVisible(true);
        AdminDashboardFrame.pack();
        AdminDashboardFrame.setExtendedState(AdminDashboardFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        AdminDashboardFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblHomeMousePressed

    private void lblArtProductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtProductsMousePressed
        
        AddProduct AddProductFrame = new AddProduct();
        AddProductFrame.setVisible(true);
        AddProductFrame.pack();
        AddProductFrame.setExtendedState(AddProductFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        AddProductFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblArtProductsMousePressed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setExtendedState(LoginFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void tblEnquiryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEnquiryMouseClicked
        
        int j = tblEnquiry.getSelectedColumn();
        int i = tblEnquiry.getSelectedRow();
        TableModel tblModel = tblEnquiry.getModel();
        
        if (j == 4) {
            

            JTextArea txtAreaMessage = new JTextArea();
            txtAreaMessage.setColumns(30);
            txtAreaMessage.setLineWrap(true);
            txtAreaMessage.setRows(7);
            txtAreaMessage.setWrapStyleWord(true);  
            txtAreaMessage.setText(tblModel.getValueAt(i, 4).toString());
            
            txtAreaMessage.setEditable(false);
            txtAreaMessage.setBackground(new Color(242,242,242));
            
            
            JOptionPane.showMessageDialog(null, txtAreaMessage, "Message",  
                                                   JOptionPane.PLAIN_MESSAGE);
            
            
        }
        
    }//GEN-LAST:event_tblEnquiryMouseClicked

    private void lblAddEventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddEventMouseEntered
        // TODO add your handling code here:
        lblAddEvent.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblAddEvent.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblAddEventMouseEntered

    private void lblAddEventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddEventMouseExited
        // TODO add your handling code here:
        lblEnquiry.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblAddEventMouseExited

    private void lblAddEventMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddEventMousePressed
        // TODO add your handling code here:
        AddEvent AddEventFrame = new AddEvent();
        AddEventFrame.setVisible(true);
        AddEventFrame.pack();
        AddEventFrame.setExtendedState(AddEventFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        AddEventFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblAddEventMousePressed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddEvent;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblArtProducts;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblEnquiry;
    private javax.swing.JLabel lblHome;
    private javax.swing.JTable tblEnquiry;
    // End of variables declaration//GEN-END:variables
}
