
package arthive;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class Event extends javax.swing.JFrame {

    String EventPrc1 = "0",EventPrc2 = "0",EventPrc3 = "0",EventPrc4 = "0";
    String EventId1 = "0",EventId2 = "0",EventId3 = "0",EventId4 = "0";
    /**
     * Creates new form Event
     */
    public Event() {
        initComponents();
        pnlArtTypeMenu.setVisible(false);
        
        pnlEvent1.setVisible(false);
        pnlEvent2.setVisible(false);
        pnlEvent3.setVisible(false);
        pnlEvent4.setVisible(false);
        
        lblMessage.setVisible(false);
        
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/arthive","root","");
            
            Statement st = con.createStatement();
            
            
                ResultSet rs = st.executeQuery("select * from tblartevents");
                
                int recordCount = 0;
                while(rs.next()){
                    recordCount++;
                 
                 switch(recordCount) {
                    case 1:
                      
                        pnlEvent1.setVisible(true);
                        lblImage1.setIcon(new ImageIcon(rs.getString("ImagePath")));
                        lblExhibitionType1.setText(rs.getString("ExhibitionType"));
                        lblFromDate1.setText(rs.getString("FromDate") + "   -");
                        lblToDate1.setText(rs.getString("ToDate"));
                        lblArtBy1.setText(rs.getString("ArtType")+ " by " + rs.getString("Artist"));
                        EventPrc1 = rs.getString("EventPrice");
                        EventId1 = rs.getString("ID");
                      break;
                    case 2:
                      
                        pnlEvent2.setVisible(true);
                        lblImage2.setIcon(new ImageIcon(rs.getString("ImagePath")));
                        lblExhibitionType2.setText(rs.getString("ExhibitionType"));
                        lblFromDate2.setText(rs.getString("FromDate") + "   -");
                        lblToDate2.setText(rs.getString("ToDate"));
                        lblArtBy2.setText(rs.getString("ArtType")+ " by " + rs.getString("Artist"));
                        EventPrc2 = rs.getString("EventPrice");
                        EventId2 = rs.getString("ID");
                      break;
                    case 3:
                      
                        pnlEvent3.setVisible(true);
                        lblImage3.setIcon(new ImageIcon(rs.getString("ImagePath")));
                        lblExhibitionType3.setText(rs.getString("ExhibitionType"));
                        lblFromDate3.setText(rs.getString("FromDate") + "   -");
                        lblToDate3.setText(rs.getString("ToDate"));
                        lblArtBy3.setText(rs.getString("ArtType")+ " by " + rs.getString("Artist"));
                        EventPrc3 = rs.getString("EventPrice");
                        EventId3 = rs.getString("ID");
                      break;
                    case 4:
                      
                        pnlEvent4.setVisible(true);
                        lblImage4.setIcon(new ImageIcon(rs.getString("ImagePath")));
                        lblExhibitionType4.setText(rs.getString("ExhibitionType"));
                        lblFromDate4.setText(rs.getString("FromDate") + "   -");
                        lblToDate4.setText(rs.getString("ToDate"));
                        lblArtBy4.setText(rs.getString("ArtType")+ " by " + rs.getString("Artist"));
                        EventPrc4 = rs.getString("EventPrice");
                        EventId4 = rs.getString("ID");
                      break;
                    
                    default:
                      
                  }
                }
                if(recordCount == 0){
                    
                    lblMessage.setVisible(true);
                    lblMessage.setText("No event to display.");
                }

            
        } catch (Exception e) {
            JOptionPane.showMessageDialog( null, e, "Message", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHome = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        lblArtType = new javax.swing.JLabel();
        lblEvent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlEventMain = new javax.swing.JPanel();
        pnlEvent1 = new javax.swing.JPanel();
        lblImage1 = new javax.swing.JLabel();
        lblGallery1 = new javax.swing.JLabel();
        lblExhibitionType1 = new javax.swing.JLabel();
        lblFromDate1 = new javax.swing.JLabel();
        lblToDate1 = new javax.swing.JLabel();
        lblArtBy1 = new javax.swing.JLabel();
        btnBookEvent1 = new javax.swing.JButton();
        pnlEvent2 = new javax.swing.JPanel();
        lblImage2 = new javax.swing.JLabel();
        lblGallery2 = new javax.swing.JLabel();
        lblExhibitionType2 = new javax.swing.JLabel();
        lblFromDate2 = new javax.swing.JLabel();
        lblToDate2 = new javax.swing.JLabel();
        lblArtBy2 = new javax.swing.JLabel();
        btnBookEvent2 = new javax.swing.JButton();
        pnlEvent3 = new javax.swing.JPanel();
        lblImage3 = new javax.swing.JLabel();
        lblGallery3 = new javax.swing.JLabel();
        lblExhibitionType3 = new javax.swing.JLabel();
        lblFromDate3 = new javax.swing.JLabel();
        lblToDate3 = new javax.swing.JLabel();
        lblArtBy3 = new javax.swing.JLabel();
        btnBookEvent3 = new javax.swing.JButton();
        pnlEvent4 = new javax.swing.JPanel();
        lblImage4 = new javax.swing.JLabel();
        lblGallery4 = new javax.swing.JLabel();
        lblExhibitionType4 = new javax.swing.JLabel();
        lblFromDate4 = new javax.swing.JLabel();
        lblToDate4 = new javax.swing.JLabel();
        lblArtBy4 = new javax.swing.JLabel();
        btnBookEvent4 = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        pnlArtTypeMenu = new javax.swing.JPanel();
        lblVisualArt = new javax.swing.JLabel();
        lblSculpture = new javax.swing.JLabel();
        lblContemporaryArt = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblHome.setText("HOME");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHomeMousePressed(evt);
            }
        });
        getContentPane().add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        lblAbout.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblAbout.setText("ABOUT");
        lblAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAboutMousePressed(evt);
            }
        });
        getContentPane().add(lblAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        lblArtType.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblArtType.setText("ART TYPE ");
        lblArtType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblArtTypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblArtTypeMouseExited(evt);
            }
        });
        getContentPane().add(lblArtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        lblEvent.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblEvent.setForeground(new java.awt.Color(255, 59, 159));
        lblEvent.setText("EVENT");
        getContentPane().add(lblEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel1.setText("Events");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1280, 320));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1280, 320));

        pnlEventMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlEventMain.setMaximumSize(new java.awt.Dimension(1280, 500));
        pnlEventMain.setMinimumSize(new java.awt.Dimension(1280, 500));
        pnlEventMain.setPreferredSize(new java.awt.Dimension(1280, 500));

        pnlEvent1.setBackground(new java.awt.Color(255, 255, 255));
        pnlEvent1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        lblImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artimages/4.Roy Villa Darjeeling new.png"))); // NOI18N

        lblGallery1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGallery1.setText("Exhibition Gallery 1");

        lblExhibitionType1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExhibitionType1.setText("Paintings");

        lblFromDate1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFromDate1.setText("January 23, 2024   -");

        lblToDate1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblToDate1.setText("January 29, 2024");

        lblArtBy1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblArtBy1.setText("VISUAL ART BY CHANDRANATH DAS");

        btnBookEvent1.setBackground(new java.awt.Color(204, 153, 0));
        btnBookEvent1.setForeground(new java.awt.Color(255, 255, 255));
        btnBookEvent1.setText("Book Event");
        btnBookEvent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookEvent1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEvent1Layout = new javax.swing.GroupLayout(pnlEvent1);
        pnlEvent1.setLayout(pnlEvent1Layout);
        pnlEvent1Layout.setHorizontalGroup(
            pnlEvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvent1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlEvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEvent1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlEvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGallery1)
                            .addComponent(lblFromDate1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(pnlEvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblToDate1)
                            .addComponent(lblExhibitionType1))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEvent1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlEvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEvent1Layout.createSequentialGroup()
                                .addComponent(lblArtBy1)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEvent1Layout.createSequentialGroup()
                                .addComponent(btnBookEvent1)
                                .addGap(112, 112, 112))))))
        );
        pnlEvent1Layout.setVerticalGroup(
            pnlEvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvent1Layout.createSequentialGroup()
                .addGroup(pnlEvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEvent1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlEvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGallery1)
                            .addComponent(lblExhibitionType1))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFromDate1)
                            .addComponent(lblToDate1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblArtBy1)
                        .addGap(18, 18, 18)
                        .addComponent(btnBookEvent1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEvent1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlEvent2.setBackground(new java.awt.Color(255, 255, 255));
        pnlEvent2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        pnlEvent2.setAlignmentX(0.1F);
        pnlEvent2.setAlignmentY(0.1F);
        pnlEvent2.setMaximumSize(new java.awt.Dimension(550, 190));
        pnlEvent2.setMinimumSize(new java.awt.Dimension(550, 190));

        lblImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artimages/4.Roy Villa Darjeeling new.png"))); // NOI18N

        lblGallery2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGallery2.setText("Exhibition Gallery 2");

        lblExhibitionType2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExhibitionType2.setText("Paintings");

        lblFromDate2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFromDate2.setText("January 23, 2024   -");

        lblToDate2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblToDate2.setText("January 29, 2024");

        lblArtBy2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblArtBy2.setText("VISUAL ART BY CHANDRANATH DAS");

        btnBookEvent2.setBackground(new java.awt.Color(204, 153, 0));
        btnBookEvent2.setForeground(new java.awt.Color(255, 255, 255));
        btnBookEvent2.setText("Book Event");
        btnBookEvent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookEvent2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEvent2Layout = new javax.swing.GroupLayout(pnlEvent2);
        pnlEvent2.setLayout(pnlEvent2Layout);
        pnlEvent2Layout.setHorizontalGroup(
            pnlEvent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvent2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlEvent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEvent2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlEvent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEvent2Layout.createSequentialGroup()
                                .addGroup(pnlEvent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGallery2)
                                    .addComponent(lblFromDate2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addGroup(pnlEvent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblToDate2)
                                    .addComponent(lblExhibitionType2))
                                .addGap(33, 33, 33))
                            .addGroup(pnlEvent2Layout.createSequentialGroup()
                                .addComponent(lblArtBy2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEvent2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBookEvent2)
                        .addGap(100, 100, 100))))
        );
        pnlEvent2Layout.setVerticalGroup(
            pnlEvent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvent2Layout.createSequentialGroup()
                .addGroup(pnlEvent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEvent2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlEvent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGallery2)
                            .addComponent(lblExhibitionType2))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEvent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFromDate2)
                            .addComponent(lblToDate2))
                        .addGap(18, 18, 18)
                        .addComponent(lblArtBy2)
                        .addGap(18, 18, 18)
                        .addComponent(btnBookEvent2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEvent2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pnlEvent3.setBackground(new java.awt.Color(255, 255, 255));
        pnlEvent3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        lblImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artimages/4.Roy Villa Darjeeling new.png"))); // NOI18N

        lblGallery3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGallery3.setText("Exhibition Gallery 3");

        lblExhibitionType3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExhibitionType3.setText("Paintings");

        lblFromDate3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFromDate3.setText("January 23, 2024   -");

        lblToDate3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblToDate3.setText("January 29, 2024");

        lblArtBy3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblArtBy3.setText("VISUAL ART BY CHANDRANATH DAS");

        btnBookEvent3.setBackground(new java.awt.Color(204, 153, 0));
        btnBookEvent3.setForeground(new java.awt.Color(255, 255, 255));
        btnBookEvent3.setText("Book Event");
        btnBookEvent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookEvent3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEvent3Layout = new javax.swing.GroupLayout(pnlEvent3);
        pnlEvent3.setLayout(pnlEvent3Layout);
        pnlEvent3Layout.setHorizontalGroup(
            pnlEvent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvent3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlEvent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEvent3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlEvent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGallery3)
                            .addComponent(lblFromDate3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(pnlEvent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblToDate3)
                            .addComponent(lblExhibitionType3))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEvent3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblArtBy3)
                        .addGap(22, 22, 22))
                    .addGroup(pnlEvent3Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnBookEvent3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlEvent3Layout.setVerticalGroup(
            pnlEvent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvent3Layout.createSequentialGroup()
                .addGroup(pnlEvent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEvent3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlEvent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGallery3)
                            .addComponent(lblExhibitionType3))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEvent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFromDate3)
                            .addComponent(lblToDate3))
                        .addGap(18, 18, 18)
                        .addComponent(lblArtBy3)
                        .addGap(18, 18, 18)
                        .addComponent(btnBookEvent3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEvent3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pnlEvent4.setBackground(new java.awt.Color(255, 255, 255));
        pnlEvent4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        lblImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artimages/4.Roy Villa Darjeeling new.png"))); // NOI18N

        lblGallery4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGallery4.setText("Exhibition Gallery 4");

        lblExhibitionType4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExhibitionType4.setText("Paintings");

        lblFromDate4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFromDate4.setText("January 23, 2024   -");

        lblToDate4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblToDate4.setText("January 29, 2024");

        lblArtBy4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblArtBy4.setText("VISUAL ART BY CHANDRANATH DAS");

        btnBookEvent4.setBackground(new java.awt.Color(204, 153, 0));
        btnBookEvent4.setForeground(new java.awt.Color(255, 255, 255));
        btnBookEvent4.setText("Book Event");
        btnBookEvent4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookEvent4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEvent4Layout = new javax.swing.GroupLayout(pnlEvent4);
        pnlEvent4.setLayout(pnlEvent4Layout);
        pnlEvent4Layout.setHorizontalGroup(
            pnlEvent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvent4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlEvent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEvent4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlEvent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGallery4)
                            .addComponent(lblFromDate4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(pnlEvent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblToDate4)
                            .addComponent(lblExhibitionType4))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEvent4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlEvent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEvent4Layout.createSequentialGroup()
                                .addComponent(lblArtBy4)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEvent4Layout.createSequentialGroup()
                                .addComponent(btnBookEvent4)
                                .addGap(94, 94, 94))))))
        );
        pnlEvent4Layout.setVerticalGroup(
            pnlEvent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvent4Layout.createSequentialGroup()
                .addGroup(pnlEvent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEvent4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlEvent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGallery4)
                            .addComponent(lblExhibitionType4))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEvent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFromDate4)
                            .addComponent(lblToDate4))
                        .addGap(18, 18, 18)
                        .addComponent(lblArtBy4)
                        .addGap(18, 18, 18)
                        .addComponent(btnBookEvent4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEvent4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        lblMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMessage.setText("No event to display.");

        javax.swing.GroupLayout pnlEventMainLayout = new javax.swing.GroupLayout(pnlEventMain);
        pnlEventMain.setLayout(pnlEventMainLayout);
        pnlEventMainLayout.setHorizontalGroup(
            pnlEventMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventMainLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnlEventMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEvent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlEvent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlEventMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEventMainLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblMessage)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEventMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(pnlEventMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlEvent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlEvent4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
        );
        pnlEventMainLayout.setVerticalGroup(
            pnlEventMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventMainLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblMessage)
                .addGap(9, 9, 9)
                .addGroup(pnlEventMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEventMainLayout.createSequentialGroup()
                        .addComponent(pnlEvent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(pnlEvent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEventMainLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(pnlEvent4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlEvent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnlEventMain);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1280, 390));

        pnlArtTypeMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlArtTypeMenu.setLayout(null);

        lblVisualArt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblVisualArt.setText("Visual Art");
        lblVisualArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVisualArtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVisualArtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVisualArtMousePressed(evt);
            }
        });
        pnlArtTypeMenu.add(lblVisualArt);
        lblVisualArt.setBounds(10, 10, 100, 23);

        lblSculpture.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSculpture.setText("Sculpture");
        lblSculpture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSculptureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSculptureMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSculptureMousePressed(evt);
            }
        });
        pnlArtTypeMenu.add(lblSculpture);
        lblSculpture.setBounds(10, 40, 90, 20);

        lblContemporaryArt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblContemporaryArt.setText("Contemporary Art");
        lblContemporaryArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblContemporaryArtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblContemporaryArtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblContemporaryArtMousePressed(evt);
            }
        });
        pnlArtTypeMenu.add(lblContemporaryArt);
        lblContemporaryArt.setBounds(10, 70, 140, 16);

        getContentPane().add(pnlArtTypeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 170, 90));

        btnLogOut.setBackground(new java.awt.Color(242, 242, 242));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.setAlignmentX(0.1F);
        btnLogOut.setAlignmentY(0.1F);
        btnLogOut.setMaximumSize(new java.awt.Dimension(79, 28));
        btnLogOut.setMinimumSize(new java.awt.Dimension(79, 28));
        btnLogOut.setPreferredSize(new java.awt.Dimension(79, 28));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 2, 85, 28));

        lblBackGround.setBackground(new java.awt.Color(255, 255, 255));
        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Art Gallery Background new.png"))); // NOI18N
        lblBackGround.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackGroundMouseClicked(evt);
            }
        });
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackGroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackGroundMouseClicked
        
        pnlArtTypeMenu.setVisible(false);
    }//GEN-LAST:event_lblBackGroundMouseClicked

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        
        lblHome.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblHome.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        
        lblHome.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMousePressed
        
        UserDashboard UserDashboardFrame = new UserDashboard();
        UserDashboardFrame.setUserValues(ArtHive.staticUserName);
        UserDashboardFrame.setVisible(true);
        
        UserDashboardFrame.pack();
        UserDashboardFrame.setExtendedState(UserDashboardFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        UserDashboardFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblHomeMousePressed

    private void lblAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseEntered
        
        lblAbout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblAbout.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblAboutMouseEntered

    private void lblAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseExited
        
        lblAbout.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblAboutMouseExited

    private void lblAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMousePressed
        
        AboutUs AboutUsFrame = new AboutUs();
        AboutUsFrame.setVisible(true);
        AboutUsFrame.pack();
        AboutUsFrame.setExtendedState(AboutUsFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        AboutUsFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblAboutMousePressed

    private void lblArtTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtTypeMouseEntered
        
        lblArtType.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblArtType.setForeground(new Color(255, 59, 159));
        pnlArtTypeMenu.setVisible(true);
    }//GEN-LAST:event_lblArtTypeMouseEntered

    private void lblArtTypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtTypeMouseExited
        
        lblArtType.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblArtTypeMouseExited

    private void lblVisualArtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualArtMouseEntered
        
        lblVisualArt.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblVisualArt.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblVisualArtMouseEntered

    private void lblVisualArtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualArtMouseExited
        
        lblVisualArt.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblVisualArtMouseExited

    private void lblVisualArtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualArtMousePressed
        
        VisualArt VisualsArtsFrame = new VisualArt();
        VisualsArtsFrame.setVisible(true);
        VisualsArtsFrame.pack();
        VisualsArtsFrame.setExtendedState(VisualsArtsFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        VisualsArtsFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblVisualArtMousePressed

    private void lblSculptureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSculptureMouseEntered
        
        lblSculpture.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblSculpture.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblSculptureMouseEntered

    private void lblSculptureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSculptureMouseExited
        
        lblSculpture.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblSculptureMouseExited

    private void lblSculptureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSculptureMousePressed
        
        Sculpture SculptureFrame = new Sculpture();
        SculptureFrame.setVisible(true);
        SculptureFrame.pack();
        SculptureFrame.setExtendedState(SculptureFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        SculptureFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblSculptureMousePressed

    private void lblContemporaryArtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContemporaryArtMouseEntered
        
        lblContemporaryArt.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblContemporaryArt.setForeground(new Color(255, 59, 159));
    }//GEN-LAST:event_lblContemporaryArtMouseEntered

    private void lblContemporaryArtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContemporaryArtMouseExited
        
        lblContemporaryArt.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblContemporaryArtMouseExited

    private void lblContemporaryArtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContemporaryArtMousePressed
        
        ContemporaryArt ContemporaryArtFrame = new ContemporaryArt();
        ContemporaryArtFrame.setVisible(true);
        ContemporaryArtFrame.pack();
        ContemporaryArtFrame.setExtendedState(ContemporaryArtFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        ContemporaryArtFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblContemporaryArtMousePressed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setExtendedState(LoginFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnBookEvent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookEvent1ActionPerformed
        
        BookNewEvent(EventPrc1, EventId1);
    }//GEN-LAST:event_btnBookEvent1ActionPerformed

    public void BookNewEvent(String EventPrc,String EventId)
    {
        ArtHive.staticEventPrice = EventPrc;
        ArtHive.staticEventId = EventId;
        
        BookEvent BookEventFrame = new BookEvent();
        BookEventFrame.setVisible(true);
        BookEventFrame.pack();
        //BookEventFrame.setExtendedState(BookEventFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        BookEventFrame.setLocationRelativeTo(null);
       // this.dispose();
       
       //JDialog dlg = new JDialog(BookEventFrame);
       //dlg.setVisible(true);
    }
    
    private void btnBookEvent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookEvent2ActionPerformed
        // TODO add your handling code here:
        BookNewEvent(EventPrc2, EventId2);
    }//GEN-LAST:event_btnBookEvent2ActionPerformed

    private void btnBookEvent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookEvent3ActionPerformed
        // TODO add your handling code here:
        BookNewEvent(EventPrc3, EventId3);
    }//GEN-LAST:event_btnBookEvent3ActionPerformed

    private void btnBookEvent4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookEvent4ActionPerformed
        // TODO add your handling code here:
        BookNewEvent(EventPrc4, EventId4);
    }//GEN-LAST:event_btnBookEvent4ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookEvent1;
    private javax.swing.JButton btnBookEvent2;
    private javax.swing.JButton btnBookEvent3;
    private javax.swing.JButton btnBookEvent4;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblArtBy1;
    private javax.swing.JLabel lblArtBy2;
    private javax.swing.JLabel lblArtBy3;
    private javax.swing.JLabel lblArtBy4;
    private javax.swing.JLabel lblArtType;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblContemporaryArt;
    private javax.swing.JLabel lblEvent;
    private javax.swing.JLabel lblExhibitionType1;
    private javax.swing.JLabel lblExhibitionType2;
    private javax.swing.JLabel lblExhibitionType3;
    private javax.swing.JLabel lblExhibitionType4;
    private javax.swing.JLabel lblFromDate1;
    private javax.swing.JLabel lblFromDate2;
    private javax.swing.JLabel lblFromDate3;
    private javax.swing.JLabel lblFromDate4;
    private javax.swing.JLabel lblGallery1;
    private javax.swing.JLabel lblGallery2;
    private javax.swing.JLabel lblGallery3;
    private javax.swing.JLabel lblGallery4;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblImage3;
    private javax.swing.JLabel lblImage4;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblSculpture;
    private javax.swing.JLabel lblToDate1;
    private javax.swing.JLabel lblToDate2;
    private javax.swing.JLabel lblToDate3;
    private javax.swing.JLabel lblToDate4;
    private javax.swing.JLabel lblVisualArt;
    private javax.swing.JPanel pnlArtTypeMenu;
    private javax.swing.JPanel pnlEvent1;
    private javax.swing.JPanel pnlEvent2;
    private javax.swing.JPanel pnlEvent3;
    private javax.swing.JPanel pnlEvent4;
    private javax.swing.JPanel pnlEventMain;
    // End of variables declaration//GEN-END:variables
}
